//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPmvccrudoperations
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Employeeid { get; set; }

        [Required(ErrorMessage = "EmployeeName is required")]
        public string EmployeeName { get; set; }

        [Required(ErrorMessage = "EmployeeSalary is required")]
        public Nullable<decimal> EmployeeSalary { get; set; }

        [Required(ErrorMessage = "EmployeeCity is required")]
        public string EmployeeCity { get; set; }
    }
}
